language: go
go: 1.4

services:
  - mongodb # 2.4.12

install:
  - export PATH=$PATH:$HOME/gopath/bin
  - go get -v github.com/leanote/leanote/app
  - go get -u github.com/revel/cmd/revel
  - ls $GOPATH/src/github.com/revel/
  # - go get github.com/revel/moudle/revel
  # - go install github.com/revel/cmd/revel
  - pwd
  - ls

script:
  - mongo --version
  - mongorestore -h localhost -d leanote --directoryperdb ./mongodb_backup/leanote_install_data/

  # gen tmp/main.go, routes/routes.go
  - go run app/cmd/main.go
  # build
  - go build -o leanote github.com/leanote/leanote/app/tmp
  # run with port 9000
  - ./leanote -importPath=github.com/leanote/leanote -runMode=dev -port=9000 &
  - sleep 10s;
  # test
  - curl http://localhost:9000
  - curl http://localhost:9000/blog
  - curl http://localhost:9000/login
  - curl http://localhost:9000/demo

  # - revel build github.com/leanote/leanote tmp
  # OK