language: go
go: 1.3

services:
  - mongodb # 2.4.12

install:
  - export PATH=$PATH:$HOME/gopath/bin
  - go get -v github.com/leanote/leanote/app
  # - go get github.com/revel/cmd/revel
  # - go install github.com/revel/cmd/revel

script:
  - mongo --version
  - mongorestore -h localhost -d leanote --directoryperdb ./mongodb_backup/leanote_install_data/
  - go test github.com/leanote/leanote/tests
  - go build -ldflags -X github.com/leanote/leanote/app
  # - revel build github.com/leanote/leanote tmp
  # OK